/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction'
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'modules/module-1-ros2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin & Simulation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'modules/module-2-digital-twin',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain',
      items: [
        {
          type: 'autogenerated',
          dirName: 'modules/module-3-ai-robot-brain',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA) Models',
      items: [
        {
          type: 'autogenerated',
          dirName: 'modules/module-4-vla',
        },
      ],
    },
    {
      type: 'category',
      label: 'Hardware Requirements',
      items: [
        {
          type: 'autogenerated',
          dirName: 'hardware-requirements',
        },
      ],
    },
  ],
};

module.exports = sidebars;